stages:
  - build-net
  - build-app
  - build-images
  - deploy

cache:
  paths:
    - src/web/node_modules/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09.7-dind

build-net:
  stage: build-net
  image: mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim
  tags:
    - k8s
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/2/packages/nuget/index.json" --name cozybus --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet restore src/BotOn.sln
    - dotnet build src/BotOn.sln -c Release

build-app:
  stage: build-app
  tags:
    - k8s
  image: node:16-alpine3.11
  script:
    - node -v
    - npm -v
    - cd src/app
    - npm --force install -g yarn
    - yarn --non-interactive
    - yarn build --non-interactive

build-images:
  stage: build-images
  tags:
    - k8s
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - echo "Building docker images"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker tag boton-identity:latest $CI_REGISTRY_IMAGE/boton-identity:latest
    - docker tag boton-web:latest $CI_REGISTRY_IMAGE/boton-web:latest
    - echo "Pushing docker images to registry"
    - docker push $CI_REGISTRY_IMAGE/boton-identity:latest
    - docker push $CI_REGISTRY_IMAGE/boton-web:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - k8s
  environment:
    name: staging
  script:
    - kubectl config get-contexts
    - echo "Creating namespace, it might exists already, so force!"
    - kubectl apply -f deploy/namespace.yaml
    - echo "Clean up"
    - kubectl delete all --all -n boton
    - echo "Adding Gitlab registry credentials"
    - kubectl delete secret docker-registry registry-credentials --ignore-not-found --namespace=boton
    - kubectl create secret docker-registry registry-credentials --docker-server=$CI_REGISTRY --docker-username=$CG_DEPLOY_USR --docker-password=$CG_DEPLOY_PWD --docker-email=$GITLAB_USER_EMAIL --namespace=boton
    - echo "Deploy to staging environment. You must supply credentials already!"
    - kubectl apply -f deploy/deployment.yaml -f deploy/service.yaml -f deploy/ingress.yaml --namespace=boton
    - kubectl rollout restart deployment boton-web-deployment --namespace=boton